Add component sticky navbar and temporary bg img
ghilannicoleta/la-fontana-app pull request #12
Opened 2023-03-25 21:36 UTC by Alteo96

2023-03-25 21:38 UTC, Alteo96 commented
Also, we should discuss with Dragos how to make the page responsive.

2023-03-25 22:15 UTC, strdr4605 requested changes
Would be nice to have a screenshot of the UI changes, so there is no need to checkout the branch locally on every small UI change.

> Hint: You can copy-paste the screenshot in the PR description. Sometimes "before" and "after" screenshot is also useful.
On macOS: CMD+Shift+4 to capture a section of the screen
----
About the responsiveness. I am not familiar with tailwindcss but probably this should do the job: https://tailwindcss.com/docs/responsive-design

2023-03-25 22:15 UTC, strdr4605 commented on client/src/components/navigation/Navigation.jsx
> +
Maybe remove 2 extra blank lines.
Each file should have only one empty line at the end.

2023-03-25 22:15 UTC, strdr4605 commented on client/src/components/navigation/Navigation.jsx
> +    <>
Looks like React fragment is redundant here, as it only has one child `<nav>`, maybe remove?😊

2023-03-25 22:15 UTC, strdr4605 commented on client/src/components/navigation/Navigation.jsx
Looks to me that we have inconsistent styles of writing JS in this project.
|Before|After|
|------|-----|
|ndentation with 4 spaces| 2 spaces|
|`Navigation(){`|`Navigation() {`|
| no semicolons| semicolons |

I would suggest adding eslint and prettier (+ VSCode plugins) to this project for consistency across the team.

2023-03-25 22:15 UTC, strdr4605 commented on client/src/App.css
> +}
Add empty line at end of file😊

2023-03-25 22:15 UTC, strdr4605 commented on client/src/App.css
> +body {
Looks to me that changes for `body` should be in https://github.com/ghilannicoleta/la-fontana-app/blob/main/client/src/index.css#L5.
And `App.css` should be removed from the project, as this project uses tailwind

2023-03-27 17:02 UTC, MaryPirtu approved these changes

2023-03-27 17:22 UTC, merged