Teo splitting components navbar
ghilannicoleta/la-fontana-app pull request #17
Opened 2023-03-27 20:49 UTC by Alteo96

PR feedback

2023-03-28 10:30 UTC, ghilannicoleta requested changes
Please rename component files to Camel Case
<img width="340" alt="image" src="https://user-images.githubusercontent.com/79923380/228208687-867a6bdc-9c40-4d76-b3be-800fbda29083.png">

2023-03-29 11:31 UTC, MaryPirtu approved these changes

2023-03-29 11:32 UTC, MaryPirtu approved these changes

2023-03-29 13:28 UTC, ghilannicoleta approved these changes

2023-03-29 13:28 UTC, merged